services:
  - type: web
    name: kohlarn-hotel
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GOOGLE_SHEET_ID
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: SERVICE_ACCOUNT_BASE64
        sync: false
